logging:
  file:
    path: /data/log/app
mybatis-plus:
  configuration:
    cache-enabled: true
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      # db-type: mysql
      # field-strategy: not_null
      id-type: auto
      logic-delete-field: isDeleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.tomhjx.lab.core.entity
spring:
  rabbitmq:
    host: "rabbitmq1.lab.local"
    port: 5672
    username: "guest"
    password: "guest"
  datasource:
    # druid:
    #   filter: stat
    #   max-active: 20
    #   initial-size: 1
    #   max-wait: 60000
    #   min-idle: 1
    #   time-between-eviction-runs-millis: 60000
    #   min-evictable-idle-time-millis: 300000
    #   validation-query: SELECT 1 FROM DUAL
    #   test-while-idle: true
    #   test-on-borrow: false
    #   test-on-return: false
    #   pool-prepared-statements: true
    #   max-open-prepared-statements: 20
    #   stat-view-servlet:
    #     enabled: false
    dynamic:
      primary: master
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://mysql8.lab.local:3306/lab?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=CONVERT_TO_NULL&allowPublicKeyRetrieval=true
          username: root
          password: 123456
app:
  history:
    file: "/data/log/spring-shell.log"